# Generated by Django 5.1.3 on 2024-11-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_url", models.CharField(default="", max_length=100)),
                ("text_data", models.CharField(default="", max_length=20000)),
            ],
            options={
                "verbose_name_plural": "User Data",
            },
        ),
    ]
